### ISSUE TITLE
does not work if user does not have multiple vote permission

### ISSUE THREAD

**Issue by ande3577** [ande3577/redmine_vote#4]
```
NoMethodError (undefined method `id' for true:TrueClass):
  plugins/redmine_vote/lib/acts_as_voteable.rb:61:in `block in voted_by_user?'
  activerecord (3.2.12) lib/active_record/associations/collection_proxy.rb:89:in `each'
  activerecord (3.2.12) lib/active_record/associations/collection_proxy.rb:89:in `method_missing'
  plugins/redmine_vote/lib/acts_as_voteable.rb:60:in `voted_by_user?'
```

**Comment by ande3577** [comment]
this is also true on original, not something i added.
